apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.external-secrets.io
    targetRevision: 2.0.1
    chart: external-secrets
    helm:
      values: |
        installCRDs: true
        serviceAccount:
          create: true
          name: external-secrets
        tolerations:
          - key: karpenter.sh/controller
            operator: Exists
            effect: NoSchedule
        webhook:
          tolerations:
            - key: karpenter.sh/controller
              operator: Exists
              effect: NoSchedule
        certController:
          tolerations:
            - key: karpenter.sh/controller
              operator: Exists
              effect: NoSchedule
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 5m
